[program:shell]
command=/usr/bin/node /app/server.js
directory=/app
user=trinket
environment=DISPLAY=":1",NODE_CONFIG_DIR="/app/config",HOME="/home/trinket",SDL_AUDIODRIVER="dummy",PYGAME_HIDE_SUPPORT_PROMPT="1"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/shell.log
stderr_logfile=/var/log/supervisor/shell.err.log
priority=300
