[program:xvnc]
command=/usr/bin/Xtightvnc :1 -rfbport 5900 -geometry 800x600 -depth 24 -ac
user=trinket
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/xvnc.log
stderr_logfile=/var/log/supervisor/xvnc.err.log
priority=100
